2023/03/13 10:31:53 [error] 7#7: *4 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/"
2023/03/13 14:53:10 [error] 7#7: *11 open() "/usr/share/nginx/html/api/auth/currentUser" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *8 open() "/usr/share/nginx/html/api/statis/monthPurchaseAmountByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *7 open() "/usr/share/nginx/html/api/auth/currentUser" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *11 open() "/usr/share/nginx/html/api/statis/monthSalesAmountByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *10 open() "/usr/share/nginx/html/api/statis/monthInboundWeightByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *9 open() "/usr/share/nginx/html/api/statis/monthOutboundWeightByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *12 open() "/usr/share/nginx/html/api/statis/monthShippingInWeightByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:10 [error] 7#7: *8 open() "/usr/share/nginx/html/api/statis/monthShippingOutWeightByDay" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 14:53:57 [error] 7#7: *1 open() "/usr/share/nginx/html/center/workplace" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /center/workplace HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:53:59 [error] 7#7: *1 open() "/usr/share/nginx/html/center/workplace" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /center/workplace HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:54:00 [error] 7#7: *1 open() "/usr/share/nginx/html/center/workplace" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /center/workplace HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:54:22 [error] 7#7: *3 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:54:25 [error] 7#7: *3 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:56:05 [error] 7#7: *1 open() "/usr/share/nginx/html/center/workplace" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /center/workplace HTTP/1.1", host: "192.168.1.10"
2023/03/13 14:56:06 [error] 7#7: *1 open() "/usr/share/nginx/html/center/workplace" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /center/workplace HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:13 [error] 7#7: *33 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:15 [error] 7#7: *33 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:16 [error] 7#7: *33 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:24 [error] 7#7: *38 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:34 [error] 7#7: *38 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:36 [error] 7#7: *38 open() "/usr/share/nginx/html/wms/asn/l" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/l HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:01:39 [error] 7#7: *38 "/usr/share/nginx/html/wms/asn/index.html" is not found (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/ HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:04 [error] 7#7: *34 open() "/usr/share/nginx/html/wms/asn/view" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/view HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:07 [error] 7#7: *34 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:11 [error] 7#7: *34 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:26 [error] 7#7: *34 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:32 [error] 7#7: *34 "/usr/share/nginx/html/wms/index.html" is not found (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/ HTTP/1.1", host: "192.168.1.10"
2023/03/13 15:02:51 [error] 7#7: *33 open() "/usr/share/nginx/html/wms/asn/list" failed (2: No such file or directory), client: 192.168.1.245, server: localhost, request: "GET /wms/asn/list HTTP/1.1", host: "192.168.1.10"
2023/03/13 17:34:22 [error] 7#7: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:23 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:34:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 17:41:06 [error] 7#7: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/account/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/account/query", host: "192.168.1.10", referrer: "http://192.168.1.10/finance/account/list"
2023/03/13 17:41:08 [error] 7#7: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/banking/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/banking/query", host: "192.168.1.10", referrer: "http://192.168.1.10/finance/banking/list"
2023/03/13 17:41:08 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/enterprise/choose HTTP/1.1", upstream: "http://172.17.0.4:8080/api/enterprise/choose", host: "192.168.1.10", referrer: "http://192.168.1.10/finance/banking/list"
2023/03/13 17:41:11 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/account/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/account/query", host: "192.168.1.10", referrer: "http://192.168.1.10/finance/account/list"
2023/03/13 17:41:12 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/account/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/account/query", host: "192.168.1.10", referrer: "http://192.168.1.10/finance/account/list"
2023/03/13 17:41:19 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/fake_list?count=5 HTTP/1.1", upstream: "http://172.17.0.4:8080/api/fake_list?count=5", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/invoice/list"
2023/03/13 17:41:22 [error] 7#7: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/contract/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/contract/query", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/contract/list"
2023/03/13 17:41:22 [error] 7#7: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/enterprise/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/enterprise/query", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/contract/list"
2023/03/13 17:41:24 [error] 7#7: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/contract/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/contract/query", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/contract/list"
2023/03/13 17:41:25 [error] 7#7: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/contract/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/contract/query", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/contract/list"
2023/03/13 17:41:25 [error] 7#7: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/contract/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/contract/query", host: "192.168.1.10", referrer: "http://192.168.1.10/bill/contract/list"
2023/03/13 18:02:00 [error] 7#7: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/asn/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/asn/query", host: "192.168.1.10", referrer: "http://192.168.1.10/wms/asn/list"
2023/03/13 18:02:01 [error] 7#7: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/wms/asn/list"
2023/03/13 18:02:01 [error] 7#7: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/asn/query HTTP/1.1", upstream: "http://172.17.0.4:8080/api/asn/query", host: "192.168.1.10", referrer: "http://192.168.1.10/wms/asn/list"
2023/03/13 18:05:03 [error] 7#7: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:03 [error] 7#7: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:21 [error] 7#7: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.4:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:05:22 [error] 7#7: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.4:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:19:59 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:01 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:02 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthPurchaseAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthPurchaseAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthSalesAmountByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthSalesAmountByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthInboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthInboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthOutboundWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthOutboundWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingInWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingInWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "POST /api/statis/monthShippingOutWeightByDay HTTP/1.1", upstream: "http://172.17.0.5:8080/api/statis/monthShippingOutWeightByDay", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
2023/03/13 18:20:15 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.245, server: localhost, request: "GET /api/auth/currentUser HTTP/1.1", upstream: "http://172.17.0.5:8080/api/auth/currentUser", host: "192.168.1.10", referrer: "http://192.168.1.10/center/workplace"
